local eq = MiniTest.expect.equality
local config = require('translate.config')

describe('config', function()
  before_each(function()
    config.reset()
  end)

  it('exposes the §10 defaults', function()
    local c = config.get()
    eq(c.provider, 'deepseek')
    eq(c.model, nil)
    eq(c.target_lang, 'Chinese')
    eq(c.temperature, 0.3)
    eq(c.thinking, false)
    eq(c.markdown_filetypes, { 'markdown' })
    eq(c.float.max_height, 0.5)
    eq(c.float.keymaps.scroll_down, '<C-d>')
    eq(c.cache.max_bytes, nil)
    eq(c.cache.grace_period, 3000)
    eq(c.request.max_concurrent, 4)
    eq(c.request.queue_size, 16)
    eq(c.request.first_byte_timeout, 30000)
    eq(c.request.stall_timeout, 20000)
    eq(c.request.max_retries, 2)
  end)

  it('defaults the cache dir under stdpath("cache")', function()
    eq(config.get().cache.dir, vim.fn.stdpath('cache') .. '/translate')
  end)

  it('merges user options recursively without dropping sibling defaults', function()
    config.setup({ target_lang = 'Cantonese', float = { keymaps = { close = '<C-c>' } } })
    local c = config.get()
    eq(c.target_lang, 'Cantonese')
    eq(c.float.keymaps.close, '<C-c>')
    eq(c.float.keymaps.scroll_down, '<C-d>')
    eq(c.float.max_height, 0.5)
  end)

  it('replaces list-like options wholesale rather than merging them', function()
    config.setup({ markdown_filetypes = { 'markdown', 'vimwiki' } })
    eq(config.get().markdown_filetypes, { 'markdown', 'vimwiki' })
  end)

  it('reports whether setup() was ever called', function()
    eq(config.is_configured(), false)
    config.setup({})
    eq(config.is_configured(), true)
  end)
end)
